[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
